### ISSUE TITLE
Web Register Page Missing Fields and Back-End Connection

### ISSUE THREAD

**Issue by OguzTNCR** [bounswe/bounswe2024group10#103]
# ℹ️ Description
* Some of the required fields are missing in the register page.
* Implemented endpoints must be connected.

# 🎯 Tasks
- [x] Add missing fields in the register page such as name, birthday, bio.
- [x] Connect the front-end with back-end using api/users/register endpoint.
- [x] Connect the front-end with back-end using api/users/login endpoint.
- [x] Connect the front-end with back-end using api/search endpoint for the search bar.

# Conclusion
* Write a conclusion as a comment before closing the issue.

**Comment by OguzTNCR** [comment]
I added the name field in the register page. Other fields were not required to create an account. But they will be added/updated from profile page in the future.

**Comment by karatashsyn** [comment]
Login and Register methods are connected to backend and implemented properly. Additionally, backend's search endpoint is used on the search page, which returns related results from backend.
