### ISSUE TITLE
Writing the Milestone-2 Report

### ISSUE THREAD

**Issue by bartukonca** [bounswe/bounswe2024group10#128]
# ℹ️ Description
* I will start working on the executive summary of the report. However, I need someone to help with "Instructions for building and deploying the application using Docker" and "URL to the GitHub code repository and the specific release tag". 

# 🎯 Tasks
* Write down the tasks and update the issue by marking them when they are done.
- [x] Executive Summary
- [x] Ali Bartu Konca Efforts
- [x] Gülşen Sabak Efforts
- [x] Hüseyin Karataş Efforts
- [x] Melih Akpınar Efforts
- [x] Nazlıcan Aka Efforts
- [x] Onur Kafkas Efforts
- [x] Oğuzhan Tuncer Efforts
- [x] Ömer Faruk Erzurumluoğlu Efforts
- [x] Yasin Atlı Efforts
- [x] Yusuf Kağan Çiçekdağ Efforts

Here is the link for the report: [Milestone 2 Report](https://github.com/bounswe/bounswe2024group10/wiki/Milestone‐2-Report)

**Comment by bartukonca** [comment]
I have written the executive summary part of the report, however I wasn't able to fill some spaces and I need you to finish them:
1.3. Code and Release Tag
1.4. Instruction for Building and Deploying the App
1.7.6. Frontend
1.7.9. Deployment
Also feel free to go over the report and add/fix places that you think can be improved

**Comment by bartukonca** [comment]
We have written the report, I am closing the issue.
