### ISSUE TITLE
Implement post endpoints

### ISSUE THREAD

**Issue by melihakpinar** [bounswe/bounswe2024group10#134]
# ℹ️ Description
* Implement endpoints related to posts. (addPost, getPosts, …)
* Estimation / Last Date: 13th May

# 🎯 Tasks
- [x] Add DTO messages (Request and response)
- [x] Implement controller class.
- [x] Implement service class(es).
- [x] Implement repository class(es).
- [x] Test if everything is OK using Postman.
