### ISSUE TITLE
Implement comment endpoints.

### ISSUE THREAD

**Issue by melihakpinar** [bounswe/bounswe2024group10#135]
# ℹ️ Description
* Implement endpoints related to comments. (addComment, removeComment, …)
* Estimation / Last Date: 13th May

# 🎯 Tasks
- [x] Add DTO messages (Request and response)
- [x] Implement controller class.
- [x] Implement service class(es).
- [x] Implement repository class(es).
- [x] Test if everything is OK using Postman.

**Comment by OmerFarukBOUN** [comment]
I have written the classes, the last touches were made by @melihakpinar
