### ISSUE TITLE
Implement like/dislike endpoints.

### ISSUE THREAD

**Issue by melihakpinar** [bounswe/bounswe2024group10#136]
# ℹ️ Description
* Implement endpoints related to likes/dislikes. (addLike, removeLike, …)
* Estimation / Last Date: 13th May

# 🎯 Tasks
- [ ] Add DTO messages (Request and response)
- [ ] Implement controller class.
- [ ] Implement service class(es).
- [ ] Implement repository class(es).
- [ ] Test if everything is OK using Postman.

**Comment by SturmR** [comment]
DTO messages, controller and service has been pushed. I will work on the repository. Not tested yet.
