### ISSUE TITLE
Implement bookmark endpoints.

### ISSUE THREAD

**Issue by melihakpinar** [bounswe/bounswe2024group10#137]
# ℹ️ Description
* Implement endpoints related to bookmarks. (addBookmark, getBookmarks, …)
* Estimation / Last Date: 13th May

# 🎯 Tasks
- [x] Add DTO messages (Request and response)
- [x] Implement controller class.
- [x] Implement service class(es).
- [x] Implement repository class(es).
- [x] Test if everything is OK using Postman.

**Comment by Pqrq** [comment]
I have implemented the Bookmark endpoint and opened a [pull request](https://github.com/bounswe/bounswe2024group10/pull/146) for my contributions.

Accordingly, I am closing this issue.
