### ISSUE TITLE
Create Post Page

### ISSUE THREAD

**Issue by karatashsyn** [bounswe/bounswe2024group10#142]
# ℹ️ Description
Post Creation page for the logged in user

# 🎯 Tasks
- [x] Create a route for post creation page.
- [x] Create input for image uploading.
- [x] Create input box for the type of the animal
- [x] Create input box for Date
- [x] Create input box for location
- [x] Create input box for post caption
- [x] Create buttons: Cancel and Post
- [x] When Post is clicked, post creation request should be sent to the backend.

**Comment by NazlicanAka** [comment]
post page is created waiting for pull request.

**Comment by NazlicanAka** [comment]
I am closing the issue because post page is done.
