### ISSUE TITLE
PostCard Button Actions

### ISSUE THREAD

**Issue by karatashsyn** [bounswe/bounswe2024group10#143]
# ℹ️ Description
Create the logic for liking, disliking, bookmarking and commenting a post.

# 🎯 Tasks
* Write down the tasks and update the issue by marking them when they are done.
- [x] Using default api instance, create the backend actions for like, dislike, bookmark and comment. 
- [x] For the postcard, create necessary loading and error states for related actions.
- [x] When action button is clicked, call the necessary api service function you have created.

**Comment by OguzTNCR** [comment]
Like, dislike and bookmark buttons are now fully functional. All api calls are handled gracefully. Also using the posts/getUserPostInteractions endpoint i showed if the registered user has done any of the actions before.
