### ISSUE TITLE
Post Detail Comment Actions

### ISSUE THREAD

**Issue by OguzTNCR** [bounswe/bounswe2024group10#145]
# ℹ️ Description
* Describe the issue clearly.
* In the PostDetail we need to implement the features of the comment part.

# 🎯 Tasks
* Write down the tasks and update the issue by marking them when they are done.
- [ ] For the comment part get the comments and list them using the api instance.
- [ ] Implement the logic so that registered users can comment on posts.
- [ ] Implement the logic so that registered users can delete the comments that they wrote.
- [ ] Implement the logic so that the ownet of the post can delete the comments

# Conclusion
* Write a conclusion as a comment before closing the issue.
