### ISSUE TITLE
APK Relase of the mobile app 

### ISSUE THREAD

**Issue by TheRealLowyer** [bounswe/bounswe2024group10#155]
# ℹ️ Description
* Initiating the APK release process for our mobile application
* This process is aimed at providing updates to end-users and enhancing the performance and usability of the application.
* APK Release
* 16.05.2024

# 🎯 Tasks
* Write down the tasks and update the issue by marking them when they are done.
- [x] Build eas.json file 
- [x] configure eas.json
- [x] create the apk using expo

# Conclusion
*

**Comment by TheRealLowyer** [comment]
Apk of the mobile app has released. You can follow the link -->  https://expo.dev//accounts/yasin.atli/projects/MySecondReaction/builds/9d63c239-c508-408d-8da1-2b475a779244
