### ISSUE TITLE
Post Detail Modal

### ISSUE THREAD

**Issue by OguzTNCR** [bounswe/bounswe2024group10#181]
# ℹ️ Description
Post cards should open the post card detail modal when detailed.

# 🎯 Tasks
* Write down the tasks and update the issue by marking them when they are done.
- [x] Create and use the Modals Context for keeping the states of modals throughout the app.
- [x] Create a ModalWrapper component for using different modal contents.
- [x] Connect a toggle function to post card for opening the related modal.
