### ISSUE TITLE
Update Wiki pages

### ISSUE THREAD

**Issue by OguzTNCR** [bounswe/bounswe2024group10#200]
# ℹ️ Description
* Since we are starting a new project we should update the wiki pages accordingly.
* Personal pages and templates should be updated.

# 🎯 Tasks
- [x] Update the personal pages.
- [x] Update the sidebar. Create an archive tab.
- [x] Move the templates and personal pages to the updated wiki.

**Comment by NazlicanAka** [comment]
@TheRealLowyer @gulsensabak and me have created archive for animal trove project and created new pages for our new project in the first lab session.
