### ISSUE TITLE
Create a wikipage about the attributes of the target audience.

### ISSUE THREAD

**Issue by melihakpinar** [bounswe/bounswe2024group10#215]
# ℹ️ Description
The target audience plays a crucial role in shaping the features and functionality of the stock forum project. To ensure the platform meets the needs and expectations of its users, it's essential to clearly define the key attributes of this audience.

# 🎯 Tasks
- [x] Define who is our target audience.
- [x] Determine the needs of our target audience.
- [x] Create a wikipage about the attributes of the target audience.

**Comment by Pqrq** [comment]
[Here](https://github.com/bounswe/bounswe2024group10/wiki/Community-Features) is the related page for this issue's tasks

I am closing this issue accordingly.
