### ISSUE TITLE
Create the main 3 milestones of the course

### ISSUE THREAD

**Issue by OmerFarukBOUN** [bounswe/bounswe2024group10#218]
# ℹ️ Description
Create the main 3 milestones of the course

# 🎯 Tasks
- [x] Create major milestone 1
- [x] Create major milestone 2
- [x] Create major milestone 3

**Comment by Pqrq** [comment]
I have initialized our major 3 milestones, as well as some other in-between milestones for October 1 Lab and Obtober 8 Lab

As there is nothing more to be done here, I am closing this issue.
