### ISSUE TITLE
Mobile App Set Up

### ISSUE THREAD

**Issue by karatashsyn** [bounswe/bounswe2024group10#241]
# ℹ️ Description
* Mobile team will be gathered and set up the codebase and make discussion about the roadmap.

# 🎯 Tasks
- [x] Meet as a mobile team
- [x] Inspect the react native basics.
- [x] Discuss about the roadmap for mobile development.

**Comment by karatashsyn** [comment]
Fixed the title as Mobile Team Planning Meet and revised the issue description.
