### ISSUE TITLE
Edit the requirements regarding to the decisions on the mobile meeting

### ISSUE THREAD

**Issue by gulsensabak** [bounswe/bounswe2024group10#248]
# ℹ️ Description
Some requirements has been changed after the mobile meeting. That's why, we need to update the requirements part of the Tradeverse project. In the tasks part, I put the determined updates that we have decided. 

# 🎯 Tasks
Update the requirements as: 
- [ ] Registered users shall be able to follow the other users.
- [ ] Admin shall be able to add only one base tag to the subforums.
- [ ] Portfolios will not be shared on feeds, only the visibility of the portfolio on the profile page will be able to get changed by portfolio owner.

**Comment by gulsensabak** [comment]
I have added all of these requirements to our [requirements page](https://github.com/bounswe/bounswe2024group10/wiki/Requirements). Can you please review it? @karatashsyn 
The added requirements points here:
1.1.7.4
1.1.7.5
1.1.5.4
1.1.1.10
1.1.1.11

**Comment by gulsensabak** [comment]
I have taken your review in lab, so I am closing this issue right now.
