### ISSUE TITLE
Discuss About Customer Presentation 1

### ISSUE THREAD

**Issue by Pqrq** [bounswe/bounswe2024group10#258]
# ℹ️ Description
We need to discuss about Customer Presentation 1; for example, what would we present, who will present, etc.

# 🎯 Tasks
- [x] Discuss about Customer Presentation 1
- [x] Decide on what features will be presented (and how they would be presented)
- [x] Decide on who will do the presentation

**Comment by gulsensabak** [comment]
We have discussed about the customer presentation. We have decided the flow of the presentation. We have shown the features taht we applied. I presented almost all parts of the presentation. @melihakpinar helped me also. @karatashsyn helped us about showing mobile application and website that we have created. Since we have completed all of the tasks, I am closing this issue.
