### ISSUE TITLE
Create App Skeleton

### ISSUE THREAD

**Issue by Pqrq** [bounswe/bounswe2024group10#267]
# ℹ️ Description
We need to create a skeleton for our mobile app.

# 🎯 Tasks
- [x] Delete Expo Boilerplate code
- [x] Create theme file for our constants
- [x] Setup Navigation System for screens related to our tab bar

**Comment by karatashsyn** [comment]
All necessary changes have been merged into codebase with [PR-269](https://github.com/bounswe/bounswe2024group10/pull/269) .
