### ISSUE TITLE
Create Post Detail Screen for Mobile

### ISSUE THREAD

**Issue by karatashsyn** [bounswe/bounswe2024group10#290]
# ℹ️ Description
* We need to create post detail screen in mobile app.

# 🎯 Tasks
- [x] Create post detail screen which will be showed when a user clicks a post to see its details.
- [x] Add post title, content and user of the post into this screen. Show parent sub forum topic in clickable format.
- [x] Show comments, comment owners, like count, discount count on this screen.

**Comment by Pqrq** [comment]
I have created the "Post Detail Screen" Screen. Some parts given above are missing, which will be fixed at the next customer presentation.

See the [related PR](https://github.com/bounswe/bounswe2024group10/pull/320)

I am closing this issue accordingly.
