### ISSUE TITLE
Create SubForum Detail Screen for Mobile

### ISSUE THREAD

**Issue by karatashsyn** [bounswe/bounswe2024group10#291]
# ℹ️ Description
* We need to create sub forum detail screen in mobile app.

# 🎯 Tasks
- [x] Create sub forum detail screen which will be showed when a user clicks to a sub forum topic.
- [x] Add sub forum title, post count info into this screen.
- [x] Add a add button into this screen to make a user capable of creating post under related sub forum topic.

**Comment by Pqrq** [comment]
I have created the "Followed Users" Screen. Some parts given above are missing, which will be fixed at the next customer presentation.

See the [related PR](https://github.com/bounswe/bounswe2024group10/pull/319)

I am closing this issue accordingly.
