### ISSUE TITLE
Write possible scenerios for the project.

### ISSUE THREAD

**Issue by bartukonca** [bounswe/bounswe2024group10#33]
# ℹ️ Description
I will start writing the possible scenerios for our project and finish it by 13th at 23.59 . If I have any questions along the way I will discuss it with my group.

# 🎯 Tasks
- [x] Write the scenerios.
- [x] Discuss with the group to see if there are any problems.
- [x] Upload them to the wiki.

**Comment by bartukonca** [comment]
I have written the scenerios and no one had an issue with them so I have put them to the wiki.
