### ISSUE TITLE
Upload/modify the research on SPARQL, Web application and Mobile application

### ISSUE THREAD

**Issue by bartukonca** [bounswe/bounswe2024group10#37]
# ℹ️ Description
* We should be more descriptive in the researches on Web applications and mobile applications. Also we need the SPARQL research to help us in the future by providing materials and references.

# 🎯 Tasks

- [x] Modify the research on Web Applications
- [x] Modify the research on Mobile Applications
- [x] Upload the research on SPARQL

**Comment by NazlicanAka** [comment]
I have added the research about SPARQL
