### ISSUE TITLE
Need help adding more requirements 

### ISSUE THREAD

**Issue by bartukonca** [bounswe/bounswe2024group10#38]
# ℹ️ Description
* We should add more requirements. I have already added some, and will continue to add more as I come up with ideas but there may be some parts where I have missed. You can check the older projects' requirements for reference. 

# 🎯 Tasks

- [x] Check older projects' requirements.
- [x] Come up with new requirement ideas (and possibly elicitation questions).
- [x] Ask the group to see if they are appropriate.
- [x] Upload the new requirements.

**Comment by bartukonca** [comment]
I have added some new requirements with the help of my group members.
