### ISSUE TITLE
Use project to see state of issues 

### ISSUE THREAD

**Issue by NazlicanAka** [bounswe/bounswe2024group10#43]
# ℹ️ Description
* I have created a project for our application. 

# 🎯 Tasks
* Write down the tasks and update the issue by marking them when they are done.
- [x] I will link issues to the project
- [x] If your issue is in progress, put the issue into "in progress section".
- [x] Link new issues to project

**Comment by NazlicanAka** [comment]
I have added all issues to project in related sections, I have not change the status open issues, you can change the status of your issue according to your progress.
