### ISSUE TITLE
Tasks for the report of Milestone-1

### ISSUE THREAD

**Issue by NazlicanAka** [bounswe/bounswe2024group10#45]
# ℹ️ Description
* We need to create a report for the first milestone.
* The deadline for the tasks is 19.03.2024 22:00.
* Write your personal efforts in descriptive manner. This is for the third part of the report.

# 🎯 Tasks
* Write your personal efforts.
- [x] Nazlıcan Aka
- [x] Mesut Melih Akpınar
- [x]  Yasin Atlı
- [x]  Yusuf Kağan Çiçekdağ
- [x] Ömer Faruk Erzurumluoğlu
- [x] Onur Kafkas
- [x]  Hüseyin Karataş
- [x]  Ali Bartu Konca
- [x]  Gülşen Şabak
- [x]  Oğuzhan Tuncer
* For the other parts of the report
- [x] 1, Executive Summary ( assigned to Ali Bartu)
- [x] 2, Project plan (assigned to Ali Bartu)
- [x] 4, Evaluation of tools and processes (assigned to Nazlıcan)

**Comment by gulsensabak** [comment]
All of the assigned tasks have done by group members.
