### ISSUE TITLE
 Link and Share Project Plan

### ISSUE THREAD

**Issue by NazlicanAka** [bounswe/bounswe2024group10#558]
ℹ️ Description
* Provide the link to the project plan created in ProjectLibre. Ensure that the plan is accessible and up to date.

🎯 Tasks

- [x] Upload the ProjectLibre file to a shared location.
- [x]  Generate a shareable link to the project plan.
- [x]  Verify the link's accessibility and permissions.
- [x]  Add the link to the repository for reference.
- [x]  Communicate the availability of the project plan to the team.

**Comment by NazlicanAka** [comment]
Here is the project plan in libre, [link](https://github.com/bounswe/bounswe2024group10/blob/main/Tradeverse-App%20Project%20Plan-3.pod)
