### ISSUE TITLE
Adding Some Missing Requirements (Unfollow,unbookmark,etc.)

### ISSUE THREAD

**Issue by Pqrq** [bounswe/bounswe2024group10#56]
# ℹ️ Description
* Issue Explanation: "Unfollow, unbookmark" parts will be added to the "Requirements" page. If there are any equivalents also missing, they will be added as well.
* Theme of the Action: Editing project requirements
* Files to Change: Requirements Page
* Estimation / Last Date: -will be filled-

# 🎯 Tasks
- [x] "Unfollow" willl be added to the "Requirements" page
- [x] "Unbookmark" willl be added to the "Requirements" page
- [x] Look for any equivalent missing requirements. If exist, fix and add them as well.

# Conclusion
* -will be filled-

**Comment by TheRealLowyer** [comment]
Unfollow (* 1.1.1.6) and unblock (* 1.1.1.8) actions of a user stated in Functional requirements/Acount seciton (* 1.1.1).
