### ISSUE TITLE
Git Research

### ISSUE THREAD

**Issue by Pqrq** [bounswe/bounswe2024group10#57]
# ℹ️ Description
* Issue explanation: Make research about Git and write it on a Wiki page
* Theme of the Action: Research
* Files to Change: None (new page will be added instead)
* Estimation / Last Date: -will be filled-

# 🎯 Tasks
* Write down the tasks and update the issue by marking them when they are done.
- [ ] Make research about the Git system
- [ ] Create a new page under the title "Research". Its title will be "Git Research"
- [ ] Explain and write your research under "Git Research" page.

# Conclusion
-will be filled-

**Comment by TheRealLowyer** [comment]
I made a research about git and its most used features. I organized my search and documented in the Git Research page that I created. I also made the relevant changes in sidebar for the Git Research page to be seen in sidebar.
