### ISSUE TITLE
Login Page Skeleton and Styling

### ISSUE THREAD

**Issue by OguzTNCR** [bounswe/bounswe2024group10#58]
# ℹ️ Description
Login.js page will be created under the pages directory. Structure and styling will be done.

# 🎯 Tasks
* Write down the tasks and update the issue by marking them when they are done.
- [x] Two States for login or register mode.
- [x] Render Email, unique username and password fields if register is selected
- [x] Render username, password fields if login state is selected. 
- [x] Besides these text fields, we need three buttons; one for switching between login and register mode, one for the main action based on the selected mode, and the other is forgot my password button.
- [x] Email, username and password  values will be kept on states. Necessary state updates will be handled on input change.

**Comment by NazlicanAka** [comment]
I have done tasks. I have created [LoginSignUp.js](https://github.com/bounswe/bounswe2024group10/blob/login-signUp-pages/src/web/animal-trove/src/pages/LoginSignUp.js) file and [LoginSignUp.css](https://github.com/bounswe/bounswe2024group10/blob/login-signUp-pages/src/web/animal-trove/src/pages/LoginSignUp.css) files.
