### ISSUE TITLE
Check and Fix Uniqueness of Attributes

### ISSUE THREAD

**Issue by Pqrq** [bounswe/bounswe2024group10#60]
# ℹ️ Description
* Issue explanation: Check the uniqueness of attributes written in the "Requirements" page. If needed to state their uniqueness, write them accordingly.
* Theme of the Action: Uniqueness checking and fixing
* Files to Change: Requirements page
* Estimation / Last Date: -will be filled-

# 🎯 Tasks
- [ ] Check the atributes in the "Requirements" page
- [ ] Check these attributes' uniquenesses and whether they have already been explicitly stated
- [ ] If needed to state but not stated already, write them accordingly

# Conclusion
-will be filled-

**Comment by TheRealLowyer** [comment]
Uniqueness of e-mail and username stated in Functional requirements/Acount seciton (* 1.1.1).
