### ISSUE TITLE
Implement Profile Page

### ISSUE THREAD

**Issue by OguzTNCR** [bounswe/bounswe2024group10#61]
# ℹ️ Description
* Profile.js file will be created under the pages folder.
* Theme of the Action
* Files to Change
* Estimation / Last Date

# 🎯 Tasks
- [x] Username, followers, following, email, user avatar and user posts should be shown.
- [x] Addititonally a settings button will be created and it will direct the user to the page in which he can edit his own profile data. This page will be named as ProfileSettings.js.
- [x] User should be able to edit personal info, password, username, avatar. Also he/she should be able to delete his/her account.

**Comment by karatashsyn** [comment]
Created two pages: Profile and ProfileSettings page. Functions handling the backend interactions are empty for now. They will be interacting with backend with the following improvements

**Comment by gulsensabak** [comment]
I think, the comment, description and tasks part are so clear. However, I think you should change the title of the issue since the person who have read the title of that issue may not understand. Maybe you can put more specific title.

**Comment by gulsensabak** [comment]
Thanks for changing. I am closing this issue right now.
