### ISSUE TITLE
Creating Post Detail Pages for the web

### ISSUE THREAD

**Issue by OguzTNCR** [bounswe/bounswe2024group10#62]
# ℹ️ Description
*  When a postcard is clicked user should be able to see the details of the clicked postcard.

# 🎯 Tasks
* Write down the tasks and update the issue by marking them when they are done.
- [x] Create a file named PostDetail.js under the pages directory.
- [x]  Username, animal photo, animal name, location info, post description, created date, comments of the post  will be rendered on the card.
- [x]  Like, dislike, comment, bookmark buttons will be positioned at the bottom of the card. Associated actions will be connected to those buttons. Also the data associated will be shown.
- [x]  A report button will be positioned to the right bottom corner of the post. Also each comment will have a report button.
- [x] Text input for posting comments will be placed in the page.

# Conclusion
* Write a conclusion as a comment before closing the issue.

**Comment by gulsensabak** [comment]
I think, we should determine more clear title for that issue. I am a team member of database group. When I read that issue title, I didn't understand what post detail page mean. I know that you will find better title but what do you think about "Creating post page for web with details"?

**Comment by TheRealLowyer** [comment]
I created the Post.js and Post.module.css files that stands for our Post page with post details.
