### ISSUE TITLE
Creating/Updating the necessary diagrams

### ISSUE THREAD

**Issue by bartukonca** [bounswe/bounswe2024group10#76]
# ℹ️ Description
Now that we have made the last changes to the ER diagram and finished the code, Ömer Faruk Erzurumluoğlu should renew the last ER diagram and upload it. And I will start working on the other necessary diagrams since the whole structure is clear. I might ask for help from the backend group. 

# 🎯 Tasks
- [x] Update ER diagram
- [x] Update Class diagram
- [x] Create Sequence diagrams
- [x] Create Use Case diagram

# Conclusion
* ...

**Comment by bartukonca** [comment]
I have created the Class Diagram, however I will wait for for the feedback of the backend group to submit it.

**Comment by OmerFarukBOUN** [comment]
I have updated the ER diagram.

**Comment by bartukonca** [comment]
I have created some sequence diagrams, I will keep adding more and in the meantime everyone is welcome to give feedback on them.

**Comment by OguzTNCR** [comment]
I created the use case diagram and put it in the corresponding page in wiki.

**Comment by bartukonca** [comment]
Thank you @TheRealLowyer for your help. I have also updated the class diagram and uploaded it

**Comment by bartukonca** [comment]
All the necessary diagrams are uploaded, we can close this issue.
