### ISSUE TITLE
Implement Java entity classes for DB integration in Spring project

### ISSUE THREAD

**Issue by melihakpinar** [bounswe/bounswe2024group10#81]
# ℹ️ Description
Create Java classes that will serve as entities in our project's database. These classes will be placed in the `models` directory of our Spring project.

# 🎯 Tasks
Develop Java entity classes that correspond to the database schema. Each class should be annotated with Spring's @Entity and should include fields, constructors, getters, and setters relevant to the database columns. Look at the ER diagram for attributes. (You can see an example [here](https://github.com/bounswe/bounswe2024group10/blob/backend-main/src/backend/animaltroove/src/main/java/com/bounswe2024group10/animaltroove/model/Animal.java).)
- [x] Implement Users class.
- [x] Implement GuestUsers class.
- [x] Implement RegisteredUsers class.
- [x] Implement Followings Class
- [x] Implement BlockedUsers class.
- [x] Implement Comments class.
- [x] Implement Likes class.
- [x] Implement Dislikes class.
- [x] Implement Posts class.
- [x] Implement Tags class.

**Comment by melihakpinar** [comment]
A friendly reminder that this issue is a blocker of #82.

**Comment by OmerFarukBOUN** [comment]
I am implementing the users.

**Comment by OmerFarukBOUN** [comment]
I have implemented the Users but I am not sure if I did it right. @melihakpinar can you review it?

**Comment by melihakpinar** [comment]
> I have implemented the Users but I am not sure if I did it right. @melihakpinar can you review it?

Sure thanks, could you please create a pull request to backend branch and add me as a reviewer?

**Comment by OmerFarukBOUN** [comment]
I am not able to push it?

**Comment by OmerFarukBOUN** [comment]
Fixed and pushed.

**Comment by OmerFarukBOUN** [comment]
While implementing like and dislike relations, there are two ways to implement these:
1. Define likeID: faster to implement and (userID, postID) tuple can be forced to bu not null and unique but we still use another ID.
2. Define a class which holds userID and postID and define the ID of likes as this class.

Which one should I implement?

**Comment by SturmR** [comment]
I’d suggest defining likeID, seems simpler and more flexible.

**Comment by OmerFarukBOUN** [comment]
We have another problem: We do not want a user to like and dislike a post at the same time. I have 3 suggestions but I do not know which one would be better to implement:
1. Use triggers in the database for check
2. Having only one "Reaction" table for like and dislike
3. Check it in a higher place

I am open for other suggestions too

**Comment by OmerFarukBOUN** [comment]
> I’d suggest defining likeID, seems simpler and more flexible.

I have done some research on it and the articles that I have come across with are doing it with defining a class. @melihakpinar @SturmR @Pqrq what are you thinking about?

**Comment by OmerFarukBOUN** [comment]
I have realized something, we do not hold special ID's for relations. Which means if we use the id method, we would probably have sql issues :/

**Comment by OmerFarukBOUN** [comment]
For ease of use in the future, i implement them as classes. Finished all the classes. There is a pending pull request.
