### ISSUE TITLE
Implement register endpoint

### ISSUE THREAD

**Issue by melihakpinar** [bounswe/bounswe2024group10#82]
# ℹ️ Description
*  The endpoint will handle the intake of user details and save them to the database using the entity models created previously.

# 🎯 Tasks
* Write down the tasks and update the issue by marking them when they are done.
- [ ] Develop the /register API endpoint within the UserController class.
- [ ] Implement the functionality to accept user registration data (e.g., username, email, password).
- [ ] If all details are eligible, add User to RegisteredUsers table.
- [ ] Return HTTP 200 OK if it is successful, if not return the error mesage.

# Conclusion
* Write a conclusion as a comment before closing the issue.

**Comment by melihakpinar** [comment]
Done
