### ISSUE TITLE
Design login and sign-up pages for the mobile app 

### ISSUE THREAD

**Issue by TheRealLowyer** [bounswe/bounswe2024group10#85]
# ℹ️  Description
* Design login and signup pages for the mobile app.
# 🎯 Tasks
* Design the login page UI:
- [x] Create a wireframe or mockup of the login page layout.
- [x] Design the UI elements for the login page (e.g., logo, username/email field, password field, login button, forgot password link).

* Design the signup page UI:
- [x] Create a wireframe or mockup of the signup page layout.
- [x] Design the UI elements for the signup page (e.g., logo, name field, username/email field, password field, confirm password field, signup button).

# Conclusion
* Once the tasks are completed, we will have a well-designed login and signup experience for the mobile app. This will improve the user experience and make it easier for users to access the app.

**Comment by TheRealLowyer** [comment]
I created and designed the Login and Signup pages. The relevant changes can be seen at yasin_mobile branch that I pushed for pull request. Also, I had to create the Main page. It is a part of the another issue.

**Comment by TheRealLowyer** [comment]
For now, user actions are blank. The connection between database and backedn API's will be done when backend team reponses.

**Comment by TheRealLowyer** [comment]
register and login endpoints are connected.
