### ISSUE TITLE
Design My Profile and Post pages for the mobile app.

### ISSUE THREAD

**Issue by TheRealLowyer** [bounswe/bounswe2024group10#86]
# ℹ️ Description
* Design My Profile and Post pages for the mobile app.
* My Profile page design (UI)
* Post page design (UI)
* 27.04.2024

# 🎯 Tasks
* Design the My Profile page UI:
- [x] Create a wireframe or mockup of the My Profile page layout.
- [x] Design the UI elements for the My Profile page (e.g., profile picture, username, bio, edit profile button, posts, followers, following).

* Design the Post page UI :
- [x] Create a wireframe or mockup of the Post page layout.
- [x] Design the UI elements for the Post page (e.g., post image, username, caption, likes, comments, share button).

# Conclusion
* Once the tasks are completed, we will have a well-designed My Profile and Post experience for the mobile app. This will improve the user experience and allow users to easily manage their profile and interact with posts.

**Comment by Pqrq** [comment]
I have completed all of the abovementioned tasks

I have opened a pull request for mobile-main branch, which includes these two pages and their "styles" pages
Page names are:
Post.js
Post.styles.js
MyProfile.js
MyProfile.styles.js

There might be some minor issues which needed to be fixed a bit.

Good luck :)

**Comment by TheRealLowyer** [comment]
Nicely done ! It works fine :) Keep up with the good work !
