### ISSUE TITLE
Dockerize the Spring Boot Application

### ISSUE THREAD

**Issue by melihakpinar** [bounswe/bounswe2024group10#98]
# ℹ️ Description
* We need to dockerize the existing Spring Boot application for easier deployment and management.

# 🎯 Tasks
- [x] Task 1: Create a Dockerfile in the project root directory.
- [x] Task 2: Build the Docker image for the application.
- [x] Task 3: Run the Docker container locally and test the application.
- [x] Task 4: Update the README.md with Docker instructions.

**Comment by SturmR** [comment]
Dockerfile created and docker image built. Will continue doing tests and writing a readme file.

**Comment by SturmR** [comment]
Readme file written.

**Comment by SturmR** [comment]
Docker container was run and tested successfully.

**Comment by SturmR** [comment]
Done.
